I2SE_Assignment2MVCApp/Controllers/CoursesController.cs
using I2SE_Assignment2MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace I2SE_Assignment2MVCApp.Controllers
{
    public class CoursesController : Controller
    {
        // GET: Courses
        // View course catalog
        public ActionResult Index()
        {
            return View(School.GetAllCourses());
        }

        // GET: Courses/Details/5
        // View details of a course
        public ActionResult Details(string id)
        {
            return View(School.GetCourse(id));
        }
    }
}

I2SE_Assignment2MVCApp/Controllers/ProfessorsController.cs
using I2SE_Assignment2MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace I2SE_Assignment2MVCApp.Controllers
{
    public class ProfessorsController : Controller
    {
        // GET: Professors/Details/5
        public ActionResult Details(string id)
        {
            return View(School.GetProfessor(id));
        }
    }
}

I2SE_Assignment2MVCApp/Views/Professors/Details.cshtml
@model I2SE_Assignment2MVCApp.Models.Professor

@{
    ViewBag.Title = "Professor Details";
}

<div class="page-header"><h1>Professor @Model.ID details</h1></div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to Catalog", "Index", "Courses", null, new { @class = "btn btn-default" })
</p>