I2SE_Assignment2MVCApp/Controllers/CoursesController.cs
using I2SE_Assignment2MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace I2SE_Assignment2MVCApp.Controllers
{
    public class CoursesController : Controller
    {
        // GET: Courses
        // View course catalog
        public ActionResult Index()
        {
            return View(School.GetAllCourses());
        }

        // GET: Courses/Details/5
        // View details of a course
        public ActionResult Details(string id)
        {
            return View(School.GetCourse(id));
        }
    }
}

I2SE_Assignment2MVCApp/Controllers/RegistrationController.cs
using I2SE_Assignment2MVCApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace I2SE_Assignment2MVCApp.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration/Index
        // View user's current courses
        public ActionResult Index()
        {
            if (School.User != null)
            {
                ICollection<Registration> myCourses = new List<Registration>();
                if (School.User is Professor)
                {
                    foreach (var item in School.GetProfessor(School.User.ID).Registrations)
                    {
                        myCourses.Add(item);
                    }
                }
                else
                {
                    foreach (var item in School.GetStudent(School.User.ID).Registrations)
                    {
                        myCourses.Add(item);
                    }
                }
                return View(myCourses);
            }
            // Has not logged in
            return RedirectToAction("Login", "Account");
        }

        // GET: Registration/Register/5
        // User registers for a course  
        public ActionResult Register(string id)
        {
            if (School.User != null)
            {
                var newReg = School.GetRegistration(id);

                if (School.Role.Contains("Student"))
                {
                    // Cannot sign up twice
                    if (newReg.StudentIDs.Contains(School.User.ID))
                    {
                        TempData["ErrorMsg"] = "You have already registered for this course.";
                        return RedirectToAction("Index", "Courses");
                    }
                    // Maximum 10 students in course
                    if (newReg.StudentIDs.Count >= 10)
                    {
                        TempData["ErrorMsg"] = "Only a maximum of 10 students are allowed.";
                        return RedirectToAction("Index", "Courses");
                    }
                    // Maximum 4 courses/semester (1 registration/course)
                    if (School.GetStudent(School.User.ID).Registrations.Count >= 4)
                    {
                        TempData["ErrorMsg"] = "You may only register for 4 courses per semester.";
                        return RedirectToAction("Index", "Courses");
                    }

                    newReg.StudentIDs.Add(School.User.ID);
                    // Write to files
                    School.Register(newReg);
                    TempData["SuccessMsg"] = "Registration Successful!";
                    return RedirectToAction("Index");
                }
                else if (School.Role.Contains("Professor"))
                {
                    // Course already has a professor
                    if (newReg.ProfessorID != null)
                    {
                        // The professor is the user
                        if (newReg.ProfessorID.Equals(School.User.ID))
                        {
                            TempData["ErrorMsg"] = "You have already registered to teach this course.";
                        }
                        // The professor is not the user
                        else
                        {
                            TempData["ErrorMsg"] = "Another professor has already registered to teach this course.";
                        }
                        return RedirectToAction("Index", "Courses");
                    }

                    newReg.ProfessorID = School.User.ID;
                    // Write to files
                    School.Register(newReg);
                    TempData["SuccessMsg"] = "Registration Successful!";
                    return RedirectToAction("Index");
                }
            }
            // Has not logged in
            TempData["ErrorMsg"] = "You must log in to register for a course.";
            return RedirectToAction("Index", "Courses");
        }

        // GET: Registration/Drop/5
        // User drops a course  
        public ActionResult Drop(string id)
        {
            if (School.User != null)
            {
                var newReg = School.GetRegistration(id);

                if (School.Role.Contains("Student"))
                {
                    if (!newReg.StudentIDs.Contains(School.User.ID))
                    {
                        TempData["ErrorMsg"] = "You have not signed up for the chosen course.";
                        return RedirectToAction("Index");
                    }
                    newReg.StudentIDs.Remove(School.User.ID);
                    // Write to files
                    School.Drop(newReg);
                    TempData["SuccessMsg"] = "Course Drop Successful!";
                    return RedirectToAction("Index");
                }
                else if (School.Role.Contains("Professor"))
                {
                    if (newReg.ProfessorID == null)
                    {
                        TempData["ErrorMsg"] = "You have not signed up to teach the chosen course.";
                        return RedirectToAction("Index");
                    }
                    newReg.ProfessorID = null;
                    // Write to files
                    School.Drop(newReg);
                    TempData["SuccessMsg"] = "Course Drop Successful!";
                    return RedirectToAction("Index");
                }
            }
            // Has not logged in
            TempData["ErrorMsg"] = "You must log in to register for a course.";
            return RedirectToAction("Index", "Courses");
        }

        // GET: Registration/Students/5
        // Professor views all students who registered for his course offerings
        public ActionResult Students(string id)
        {
            ICollection<Student> myStudents = new List<Student>();
            var reg = School.GetRegistration(id);
            foreach (var studentID in reg.StudentIDs)
            {
                myStudents.Add(School.GetStudent(studentID));
            }
            ViewBag.Course = School.GetCourse(reg.CourseID);
            return View(myStudents);
        }

        // GET: Registration/Check
        // Student view billing info
        public ActionResult Check()
        {
            if (School.User != null)
            {
                ICollection<Course> myCourses = new List<Course>();
                if (School.User is Student)
                {
                    foreach (var item in School.GetStudent(School.User.ID).Registrations)
                    {
                        myCourses.Add(School.GetCourse(item.CourseID));
                    }
                }
                return View(myCourses);
            }
            // Has not logged in as Student
            TempData["ErrorMsg"] = "You must sign in as a student to continue.";
            return RedirectToAction("Index");
        }
    }
}

I2SE_Assignment2MVCApp/Views/Courses/Details.cshtml
@model I2SE_Assignment2MVCApp.Models.Course

@{
    ViewBag.Title = "Course Details";
    int currentSize = Model.Registration.StudentIDs == null ? 0 : Model.Registration.StudentIDs.Count;
}

<div class="page-header"><h1>Course @Model.ID details</h1></div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            Current Size
        </dt>

        <dd>
            @currentSize
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Sign up", "Register", "Registration", new { id = Model.ID }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to Catalog", "Index", null, new { @class = "btn btn-default" })
</p>

I2SE_Assignment2MVCApp/Views/Courses/Index.cshtml
@model IEnumerable<I2SE_Assignment2MVCApp.Models.Course>

@{
    ViewBag.Title = "Course Catalog";
}

<div class="page-header"><h1>Course catalog</h1></div>

@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-warning fade in">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["ErrorMsg"]
    </div>
}

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Department)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cost)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "Details", new { id = item.ID })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Sign up", "Register", "Registration", new { id = item.ID }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>